apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "hello-service"
  name: "hello-service"
spec:
  ports:
  - port: 9090
    protocol: "TCP"
    targetPort: 9090
  selector:
    app: "hello-service"
  type: "NodePort"

